config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  
  resources :recipes do
    resources :recipe_foods, only: [:new, :create, :destroy, :show, :edit, :update]
  end
  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :public_recipes, only: [:index]
  get 'shopping_list', to: 'shopping_lists#index', as: 'shopping_list'
  root to: 'recipes#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :read, :all
    can :manage, Recipe, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_food

  validates :user, presence: true
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_or_equal_to: 0 }
  validates :measurement_unit, presence: true
  validates :quantity, numericality: { greater_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, foreign_key: 'recipe_id', dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy

  def self.public_recipes
    where(public_recipe: true)
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_or_equal_to: 0 }

  # recipe_food should include (foods, recipes)
  def value
    return 'no food error' unless food

    food.price * quantity
  end

  def self.total_price(recipe_foods)
    recipe_foods.reduce(0) { |sum, recipe_food| sum + recipe_food.value }
  end

  def self.shopping_list(user)
    recipe_foods = RecipeFood.joins(:food)
      .select('recipe_foods.food_id, foods.name, foods.price, SUM(recipe_foods.quantity) as quantity')
      .group('recipe_foods.food_id, foods.name, foods.price')

    user_foods = Food.where(user:)

    shop_list = []
    recipe_foods.each do |recipe_food|
      food = user_foods.select { |el| el.id == recipe_food.food_id }
      if food.length == 1
        food = food[0]
        recipe_food.quantity -= food.quantity if food
        recipe_food.price *= recipe_food.quantity

        shop_list << recipe_food if recipe_food.quantity.positive?
      else
        shop_list << recipe_food
      end
    end
    shop_list
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes, foreign_key: 'user_id', dependent: :destroy
  has_many :foods
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :foods, foreign_key: :user_id
  has_many :recipe_foods, through: :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.where(user: current_user)
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user = current_user

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_url, notice: 'Food was successfully created.' }
        format.json { render :index, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update; end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    RecipeFood.destroy_by(food: @food)
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = public_recipes
  end

  private

  def public_recipes
    Recipe.where(public_recipe: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!
  def new
    @recipe_food = RecipeFood.new
    @foods = Food.where(user: current_user)
    @recipe = Recipe.find(params[:recipe_id])
  end

  def show; end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe = Recipe.find(params[:recipe_id])
    @recipe_food.food = Food.find(params[:recipe_food][:id])

    if @recipe_food.save
      redirect_to recipe_path(@recipe_food.recipe_id), notice: 'Ingredient has been added successfully!'

    else
      redirect_to recipe_path(@recipe_food.recipe_id), notice: 'Error Happened'
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to recipe_url(params[:recipe_id]), notice: 'Ingredient was successfully destroyed.'
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @foods = Food.where(user: current_user)
    @recipe = Recipe.find(params[:recipe_id])
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.update(recipe_food_params)
    redirect_to recipe_path(@recipe_food.recipe_id), notice: 'Ingredient was successfully updated.'
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = current_user.recipes
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find_by_id(params[:id])
    @current_user = current_user
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    @recipe.public_recipe = params[:recipe][:public_recipe] == '1'

    if @recipe.save
      redirect_to @recipe
    else
      render :new
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe) }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  def public_recipes
    @recipes = Recipe.where(public_recipe: true)
  end

  # Use callbacks to share common setup or constraints between actions.
  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:title, :description, :preparation_time, :cooking_time, :user_id, :public_recipe)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def index
    @shop_list = RecipeFood.shopping_list(current_user)

    @total_price = @shop_list.reduce(0) { |sum, el| sum + el.price }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/_food.html.erb
<tr id="<%= dom_id food %>">
    <td><%= food.name %></td>
    <td><%= food.measurement_unit %></td>
    <td><%= food.price %></td>
    <td>
      <%= button_to "Remove", food, method: :delete, class: "delete-button delete-food" %>
    </td>

</tr>

app/views/foods/_form.html.erb
<div class="form-container">
<div class="form">
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, placeholder: "Tomato ..", class: "form--input" %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit, placeholder: "eg: kg, grams, unit ..", class: "form--input" %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, placeholder: "eg: 10 '$'", class: "form--input" %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity, placeholder: "30 'gram'", class: "form--input" %>
  </div>
  
   <div class="form__group">
      <%= form.submit "Add Food", class: "form--submit" %>
      <%= link_to "Cancel", foods_path, class: "form-cancel-link" %>
    </div>
<% end %>

</div>
</div>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
  <div class="foood-container">

        <div class="foods">
        <%= button_to "Add Food", new_food_path, method: :get, class:"save-button add-food" %>
        <table class="food-table">
            <tr>
            <th>Food</th>
            <th>Measurement unit</th>
            <th>Unit price</th>
            <th>Actions</th>
            </tr>
            <% @foods.each do |food| %>
            <%= render food %>
            <% end %>
        </table>
        </div>
 </div>

app/views/foods/new.html.erb
<div class="form">

<div class="row btn-back">
  <%= link_to "Back", foods_path %>
</div>

<div>
  <h2 class="head-title">New food</h2>
  <%= render "form", food: @food %>
</div>

<div class="bg-plate-reversed"></div>

</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CooksCorner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "index", "data-turbo-track": "reload" %>
  </head>

  <body>
  <div class="overlay">
  <header> <%= render partial: "shared/navbar" %></header>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  </div>
</body>
</html>

app/views/public_recipes/index.html.erb
<section class="recipes public">
  <% if @recipes.empty? %>
    <p class="empty-recipes">No public recipes.</p>
  <% else %>
    <% @recipes.each do |recipe| %>
      <div class="recipe-item">
            <div class="block1">
              <h4 class="link"><%= link_to recipe.title, recipe_path(recipe) %></h4>
              <p class="usernames">By: <%= recipe.user.name %></p>
            </div>
            <div>
              <h4  class="recipe-det">Total food: <span><%= recipe.recipe_foods.length %></span></h4>
              <h4  class="recipe-det">Total price: <span>$<%= RecipeFood.total_price(recipe.recipe_foods) %></span></h4>
            </div>
      </div>
    <% end %>
  <% end %>
</section>

app/views/recipe_foods/edit.html.erb
<div class="row btn-back">
  <%= link_to "Back", "/recipes/#{@recipe.id}" %>
</div>

<div class="column add-form-margin">
  <h1>Edit Ingredient</h1>
  <%= form_with model: @recipe_food, url: recipe_recipe_food_path(recipe_id: @recipe_food.recipe_id, id: @recipe_food.id), method: :patch do |f| %>
    <%= f.hidden_field :id, value: @recipe_food.id %>
    <%= f.hidden_field :recipe_id, value: @recipe_food.recipe_id %>

    <%= f.label :food_id, "Select Ingredient" , style: "display: block" %>

    <%= f.select :food_id, @foods.map { |food| [food.name, food.id] }, {}, { class: "input-default" } %>

    <%= f.label :food_id, "Quantity" , style: "display: block" %>
    <%= f.number_field :quantity, placeholder: "eg: 30 'gram'", class: "input-default" %>
    <br/>
    <%= f.submit "Update Ingredient", class: "btn-bg-red-big" %>
  <% end %>
</div>

app/views/recipe_foods/new.html.erb
<div class="new-ingredient">
<div class="row btn-back">
  <%= link_to "Back", "/recipes/#{@recipe.id}" %>
</div>

<div class="add-form-margin">

  <h1>Add Ingredients</h1>

  <%= form_with(model: @recipe_food, url: "/recipes/#{@recipe.id}/recipe_foods/")  do |form| %>
    <% if @recipe_food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@recipe_food.errors.count, "error") %> prohibited this @recipe_food from being saved:</h2>

        <ul>
          <% @recipe_food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="ingredient-form"> 
    <%= form.label :name, "Select a food:", class: "ingredint-form-item" %>
    <%= form.select :id, 
      options_for_select(@foods.map { |f| [f.name, f.id] }), 
      {}, { class: "ingredint-form-item" } %><br>
      <%= form.label :quantity, placeholder: "10 'kg'..",class: "ingredint-form-item" %>
      <%= form.number_field :quantity, class: "quantity-input" %>
      <br>
  
      <%= form.submit class: "save-button save-button2" %>
    </div>
  <% end %>
</div>
</div>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, id: "recipe_form") do |form| %>
  <% if recipe.errors.any? %>
    <div id="recipe_errors" class="error_message">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form_group">
    <%= form.label :title, style: "display: block", class: "form_labels" %>
    <%= form.text_field :title, id: "recipe_title", class: "form_control" %>
  </div>

  <div class="form_group">
    <%= form.label :description, style: "display: block", class: "form_labels" %>
    <%= form.text_area :description, id: "recipe_description", class: "form_control" %>
  </div>

  <div class="form_group">
    <%= form.label :preparation_time, style: "display: block", class: "form_labels" %>
    <%= form.number_field :preparation_time, id: "recipe_preparation_time", class: "form_control" %>
  </div>

  <div class="form_group">
    <%= form.label :cooking_time, style: "display: block", class: "form_labels" %>
    <%= form.number_field :cooking_time, id: "recipe_cooking_time", class: "form_control" %>
  </div>

  <div class="form_group">
    <%= form.label :user_id, style: "display: block", class: "form_labels" %>
    <%= form.text_field :user_id, value: current_user.id, readonly: true, id: "recipe_user_id", class: "form_control" %>
  </div>

  <div class="form_group">
    <%= form.submit "Save Recipe", class: "btn btn_primary" %>
  </div>
<% end %>

app/views/recipes/_recipe1.html.erb
<div id="<%= dom_id recipe %>" class="recipe_container">
  <div class="block1 block1-edited">
    <h4 class="recipe_title">
      <%= link_to recipe.title, recipe %>
    </h4>
    <p><%= button_to "Delete recipe", recipe_path(recipe), class: "remove", method: :delete, data: { confirm: "Are you sure you want to delete this recipe?" }, class: "delete-button" %></p>
  </div>
    <p class="recipe_description">
      <%= recipe.description %>
    </p>

</div>

app/views/recipes/_recipe2.html.erb
<div id="<%= dom_id recipe %>" class="recipe_container2">
  <div class="block3">
    <h4 class="recipe_title2">
      <%= link_to recipe.title, recipe %>
    </h4>

  </div>
    <p class="recipe_description2">
      <br>Preparation Time: <%= recipe.preparation_time %> minutes</br>
      <br>Cooking Time: <%= recipe.cooking_time %> minutes</br>
      <br>Description: <%= recipe.description %></br>
    </p>
    <%= form_with(model: recipe, id: "recipe_form", remote: true) do |form| %>
      <div class="form_group save-public">
      <div class="form_group save-public">
      <%= form.label :public_recipe, style: "display: block", class: "form_label" do %>
        Public 
        <div class="toggle-switch">
          <%= form.check_box :public_recipe, id: "recipe_public_recipe", class: "form_check_input", onchange: "this.form.submit()" %>
          <span class="slider round"></span>
        </div>
      <% end %>
    </div>
      
    <% end %>

</div>

app/views/recipes/edit.html.erb
<h1 class="page_title">Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div class="recipe_links">
  <%= link_to "Show this recipe", @recipe, class: "recipe_show_link" %> |
  <%= link_to "Back to recipes", recipes_path, class: "recipe_back_link" %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<section id="my-recipes">
  <h1 id="recipes-header">Recipes</h1>

  <div id="recipes">
    <% @recipes.each do |recipe| %>
      <%= render partial: 'recipe1', locals: { recipe: recipe } %>
    <% end %>
  </div>

  <%= link_to "New recipe", new_recipe_path, class: "new-recipe" %>
</section>

app/views/recipes/new.html.erb
<section id="new-recipe-section">
<h1 class="new-recipe-header">New recipe</h1>
<%= render "form", recipe: @recipe %>

<br>

<div class="recipe_links">
  <%= link_to "Back to recipes", recipes_path, class: "recipe_back_link" %>
</div>
</section>

app/views/recipes/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Public Recipes</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <p class="notice" style="color: green"><%= notice %></p>
    <section class="view_recipe">
    <div class="display">
    <%= render partial: 'recipe2', locals: { recipe: @recipe } %>
        <div class="recipe-buttons2">
          <% if user_signed_in? %>
            <%= link_to "Generate Shopping List", shopping_list_path, class: "recipe-action-btn" %>
          <% end %>
        <% if @recipe.user == current_user %>
        <a href= <%= "/recipes/#{@recipe.id}/recipe_foods/new" %> class="recipe-action-btn">
    Add Ingredient
      </a>
       <% end %>
    </div>
  <br>

    
    <table id="recipe_table" class="food-table">
      <thead class="recipe_table_head">
        <tr class="recipe_table_row">
          <th class="recipe_table_header">Food</th>
          <th class="recipe_table_header">Quantity</th>
          <th class="recipe_table_header">Value</th>
          <% if @recipe.user == current_user %>
            <th class="recipe_table_header">Action</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
      <% @recipe.recipe_foods.each do |recipe_food| %>
      <tr>
          <td><%= recipe_food.food.name %></td>
          <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></td>
          <td>$ <%= recipe_food.value %></td>
          <td>
          <% if @recipe.user == current_user %>
          <div class="row btns">
           <%= button_to "Remove", recipe_recipe_food_path(recipe_id: @recipe.id, id: recipe_food.id), class: "delete-button delete-food", method: :delete %>
          </div>
          <% end %>
          </td>
      </tr>
    <% end %>
      </tbody>
    </table>
</div> 
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="nav-group">
  <% if user_signed_in? %>
    <%= link_to "Recipes", public_recipes_path, class: "btn" %>
    <%= link_to "My Recipes", recipes_path, class: "btn" %>
    <%= link_to "Foods", foods_path, class: "btn" %>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn" %>
  <% else %>
    <h1>Welcome to our recipe app</h1>
  <% end %>
</div>

app/views/shopping_lists/index.html.erb
<div class="form">
  <h2>Shopping List</h2>
  <div>
    <p>
      Amount of food items to buy: <%= @shop_list.length %>
    </p>
    <p>
      Total value of food neeeded: <%= @total_price %>
    </p>
  </div>

  <table class="table">
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>
    <% @shop_list.each do |recipe_food| %>
      <tr>
        <td class="list"><%= recipe_food.name %></td>
        <td class="list"><%= recipe_food.quantity %></td>
        <td class="list"><%= recipe_food.price %></td>
      </tr>
    <% end %>

    <% if @shop_list.length == 0 %>
      <tr>
        <td colspan="10">
            <p>Empty list of elements</p>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/index.html.erb
<%= button_to "Logout", destroy_user_session_path, method: :delete %>
<p>A list of all users</p>